name: Docker_Downloader
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Download Image using Skopeo
        run: |
          # 1. 安装 skopeo
          sudo apt-get update
          sudo apt-get install -y skopeo

          # 2. 直接将镜像拉取并保存为 docker-archive 格式，并直接用 gzip 压缩
          echo "正在通过 Skopeo 直接封包镜像 (不解压)..."
          skopeo copy --src-tls-verify=false \
            docker://docker.io/mltooling/ml-workspace-gpu:latest \
            docker-archive:ml-gpu.tar:mltooling/ml-workspace-gpu:latest

          echo "正在压缩文件以减小体积..."
          gzip ml-gpu.tar

          echo "打包完成，文件大小："
          du -sh ml-gpu.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ml-gpu-package
          path: ml-gpu.tar.gz
          retention-days: 1
